apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: todo-api:latest
          envFrom:
            - configMapRef:
                name: todo-api-config
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: todo-api-data
              mountPath: /data
      volumes:
        - name: todo-api-data
          persistentVolumeClaim:
            claimName: todo-api-data